config/routes.rb
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

Rails.application.routes.draw do
  resource :dashboard_async_blocks, only: %i[show create]

  resources :dashboards do
    member do
      post :update_layout_setting
      post :add_block
      post :remove_block
      post :order_blocks
    end
  end
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2016 - 2021 Alexander Meindl <https://github.com/alexandermeindl>, alphanodes.
# See <https://github.com/AlphaNodes/additionals>.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

class DashboardsController < ApplicationController
  menu_item :dashboards

  before_action :find_dashboard, except: %i[index new create]
  before_action :find_optional_project, only: %i[new create index]
  before_action :authorize_global

  accept_atom_auth :index, :show
  accept_api_auth :index, :show, :create, :update, :destroy

  rescue_from Query::StatementInvalid, with: :query_statement_invalid

  helper :queries
  helper :issues
  helper :activities
  helper :watchers
  helper :dashboards
  helper :dashboards_routes
  helper :dashboards_queries
  helper :dashboards_settings

  include DashboardsQueriesHelper
  include DashboardsRoutesHelper
  include QueriesHelper
  include WatchersHelper
  include SortHelper

  def index
    case params[:format]
    when 'xml', 'json'
      @offset, @limit = api_offset_and_limit
    else
      @limit = per_page_option
    end

    scope = Dashboard.visible
    @query_count = scope.count
    @query_pages = Paginator.new @query_count, @limit, params['page']
    @dashboards = scope.sorted
                       .limit(@limit)
                       .offset(@offset)
                       .to_a

    respond_to do |format|
      format.html { render_error status: 406 }
      format.api
    end
  end

  def show
    respond_to do |format|
      format.html { head :not_acceptable }
      format.js if request.xhr?
      format.api
    end
  end

  def new
    @dashboard = Dashboard.new(project: @project,
                               user: User.current)
    @dashboard.dashboard_type = assign_dashboard_type
    @allowed_projects = @dashboard.allowed_target_projects
  end

  def edit
    return render_403 unless @dashboard.editable_by? User.current

    respond_to do |format|
      format.html
      format.api
    end
  end

  def create
    @dashboard = Dashboard.new(user: User.current)
    @dashboard.safe_attributes = params[:dashboard]
    @dashboard.dashboard_type = assign_dashboard_type
    @dashboard.role_ids = params[:dashboard][:role_ids] if params[:dashboard].present?

    @allowed_projects = @dashboard.allowed_target_projects

    if @dashboard.save
      flash[:notice] = l :notice_successful_create

      respond_to do |format|
        format.html { redirect_to dashboard_link_path(@dashboard) }
        format.api  do
          render action: 'show', status: :created, location: dashboard_url(@dashboard, project_id: @project)
        end
      end
    else
      respond_to do |format|
        format.html { render action: 'new' }
        format.api  { render_validation_errors @dashboard }
      end
    end
  end

  def update
    return render_403 unless @dashboard.editable_by? User.current

    @dashboard.safe_attributes = params[:dashboard]
    @dashboard.role_ids = params[:dashboard][:role_ids] if params[:dashboard].present?

    if @dashboard.save
      flash[:notice] = l :notice_successful_update
      respond_to do |format|
        format.html { redirect_to dashboard_link_path(@dashboard) }
        format.api  { head :ok }
      end
    else
      respond_to do |format|
        format.html { render action: 'edit' }
        format.api  { render_validation_errors @dashboard }
      end
    end
  end

  def destroy
    return render_403 unless @dashboard.destroyable_by? User.current

    begin
      @dashboard.destroy
      flash[:notice] = l :notice_successful_delete
      respond_to do |format|
        format.html { redirect_to home_path }
        format.api  { head :ok }
      end
    rescue ActiveRecord::RecordNotDestroyed
      flash[:error] = l :error_remove_db_entry
      redirect_to dashboard_path(@dashboard)
    end
  end

  def query_statement_invalid(exception)
    logger&.error "Query::StatementInvalid: #{exception.message}"
    session.delete dashboard_query_session_key('dashboard')
    render_error l(:error_query_statement_invalid)
  end

  def update_layout_setting
    block_settings = params[:settings] || {}
    block_settings.each do |block_id, settings|
      @dashboard.update_block_settings block_id, settings.to_unsafe_hash
    end
    @dashboard.save
    @updated_blocks = block_settings.keys
  end

  ##
  # Adds a new block on top of the page
  #
  # @params params[:block_id] Id of the block to add, i.e., button__1
  #
  def add_block
    @block_id = params[:block_id]
    added = @dashboard.add_block @block_id
    saved = @dashboard.save
    if added && saved
      respond_to do |format|
        format.html { redirect_to dashboard_link_path(@dashboard) }
        format.js
      end
    else
      flash[:error] = "#{@dashboard.name}: #{@dashboard.errors.full_messages.join(', ')}"
      redirect_to dashboard_link_path(@dashboard)
    end
  end

  ##
  # Removes the given block from the page
  #
  # @params params[:block_id] Id of the block to add, i.e., button__1
  #
  def remove_block
    @block_id = params[:block_id]
    @dashboard.remove_block @block_id
    @dashboard.save
    respond_to do |format|
      format.html { redirect_to dashboard_link_path(@dashboard) }
      format.js
    end
  end

  # Change blocks order
  # params[:group] : group to order (top, left or right)
  # params[:block_ids] : array of block ids of the group
  def order_blocks
    @dashboard.order_blocks params[:group], params[:block_ids]
    @dashboard.save
    @block_ids = params[:block_ids]
  end

  private

  def assign_dashboard_type
    if params['dashboard_type'].present?
      params['dashboard_type']
    elsif params['dashboard'].present? && params['dashboard']['dashboard_type'].present?
      params['dashboard']['dashboard_type']
    elsif @project.nil?
      DashboardContentWelcome::TYPE_NAME
    else
      DashboardContentProject::TYPE_NAME
    end
  end

  def find_dashboard
    @dashboard = Dashboard.find params[:id]
    raise ::Unauthorized unless @dashboard.visible?

    @project = @dashboard.project
    @can_edit = @dashboard&.editable?
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2016 - 2021 Alexander Meindl <https://github.com/alexandermeindl>, alphanodes.
# See <https://github.com/AlphaNodes/additionals>.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

module DashboardsHelper
  def dashboard_async_cache(dashboard, block_id, async, settings, &content_block)
    cache render_async_cache_key(dashboard_async_blocks_path(dashboard.async_params(block_id, async, settings))),
          expires_in: async[:cache_expires_in] || DashboardContent::RENDER_ASYNC_CACHE_EXPIRES_IN,
          skip_digest: true, &content_block
  end

  # candidate for a service_object?
  def dashboard_async_required_settings?(settings, async)
    return true if async[:required_settings].blank?
    return false if settings.blank?

    async[:required_settings].each do |required_setting|
      return false if settings.exclude?(required_setting) || settings[required_setting].blank?
    end

    true
  end

  # candidate for a service object
  def dashboard_sidebar?(params)
    enabled = params['enable_sidebar']
    return false if enabled.blank?

    RedmineDashboards.true? enabled
  end

  # Renders a single block content - candidate for a service object
  def render_dashboard_block_content(block_id, block_object, dashboard, overwritten_settings = {})
    settings = dashboard.layout_settings(block_id)
    settings = settings.merge(overwritten_settings) if overwritten_settings.present?
    partial = block_object[:partial]
    partial_locals = build_dashboard_partial_locals block_id, block_object, settings, dashboard

    if block_object[:query_block] || block_object[:async]
      render partial: 'dashboards/blocks/async', locals: partial_locals
    elsif partial
      begin
        render partial: partial, locals: partial_locals
      rescue ActionView::MissingTemplate
        Rails.logger.warn "Partial \"#{partial}\" missing for block " \
                          "\"#{block_id}\" found in #{dashboard.name} (id=#{dashboard.id})"
        nil
      end
    else
      # Required for legacy blocks only!
      block_object.send "render_#{block_object[:type]}_block", block_id, settings, dashboard
    end
  end

  # candidate for service object
  def build_dashboard_partial_locals(block_id, block_object, settings, dashboard)
    partial = BlockPartial.new(block: { id: block_id, object: block_object },
                               settings: settings,
                               dashboard: dashboard,
                               params: params)
    partial.locals
  end

  # issue counter and query list - candidate for a service/query object
  def options_for_query_select(klass, project, selected = nil)
    tag.option + options_from_collection_for_select(queries(klass, project), :id, :name, selected)
  end

  # issue counter and query list - candidate for a service/query object
  def grouped_options_for_query_select(klass, project, selected = nil)
    all_queries = queries(klass, project)
    group = { "#{l(:label_my_queries)}": all_queries.select(&:is_private?).pluck(:name, :id),
              "#{l(:label_query_plural)}": all_queries.reject(&:is_private?).pluck(:name, :id) }

    tag.option + grouped_options_for_select(group.to_a, selected)
  end

  private

  # candidate for a service/query object
  ##
  # sidebar_queries cannot be used because descendant classes are included
  # this changes on class loading
  # queries = klass.visible.global_or_on_project(@project).sorted.to_a
  #
  def queries(klass, project)
    klass
      .visible
      .global_or_on_project(project)
      .where(type: klass.to_s)
      .sorted.to_a
  end

  # candidate for a service object
  def resently_used_dashboard_save(dashboard, project = nil)
    user = User.current
    dashboard_type = dashboard.dashboard_type
    recently_id = user.pref.recently_used_dashboard dashboard_type, project
    return if recently_id == dashboard.id || user.anonymous?

    user.pref.recently_used_dashboards[dashboard_type] = dashboard.id
    user.pref.save
  end

  ##
  # Copied from Redmine ReportsHelper module
  #
  def aggregate(data, criteria)
    a = 0
    data&.each do |row|
      match = 1
      criteria&.each do |k, v|
        next if (row[k].to_s == v.to_s) ||
                (k == 'closed' &&
                  (v.zero? ? ['f', false] : ['t', true]).include?(row[k]))

        match = 0
      end
      a += row['total'].to_i if match == 1
    end
    a
  end
end

app/views/dashboards/blocks/_activity_settings.html.erb
<%
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2016 - 2021 Alexander Meindl <https://github.com/alexandermeindl>, alphanodes.
# See <https://github.com/AlphaNodes/additionals>.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
%>

<%= tag.div class: 'box tabular settings' do %>
  <%= tag.p dashboards_settings_numberfield :max_entries,
                                            value: settings.fetch(:max_entries, block_object.default_max_entries),
                                            tag_name: "settings[#{block_id}][max_entries]",
                                            min: 1, max: 100, required: true %>
  
  <%= tag.p dashboards_settings_checkbox :me_only,
                                          label: l(:label_only_my_activities),
                                          active_value: settings[:me_only],
                                          tag_name: "settings[#{block_id}][me_only]" %>
<% end %>

app/views/dashboards/blocks/_async.html.erb
<%
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2016 - 2021 Alexander Meindl <https://github.com/alexandermeindl>, alphanodes.
# See <https://github.com/AlphaNodes/additionals>.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
%>

<% with_async = dashboard_async_required_settings?(settings, async) %>
<% unless with_async %>
  <%= tag.h3 settings[:title].presence || block_object[:label] %>
<% end %>

<% if @can_edit && \
     block_object[:no_settings].blank? && \
     (!block_object.key?(:with_settings_if) || block_object[:with_settings_if].call(@project)) %>

  <%= tag.div id: "#{block_id}-settings", style: "#{'display: none;' if with_async}" do %>
    <%= form_tag(update_layout_setting_dashboard_path(dashboard), remote: true) do %>
      <%= render  partial: block_object[:settings_partial].presence || "#{async[:partial]}_settings",
                  locals: build_dashboard_partial_locals(block_id,
                                                         block_object,
                                                         settings,
                                                         dashboard).merge(with_async: with_async) %>

      <%= tag.p do%>
        <%= submit_tag l(:button_save) %>
        <%= link_to_function l(:button_cancel), "$('##{block_id}-settings').toggle();" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<% if with_async %>
  <%= render_async_cache dashboard_async_blocks_path(dashboard.async_params(block_id, async, settings)) do %>
    <%= tag.div class: 'clear-both' %>
    <%= tag.p do %>
      <%= tag.i class: 'fas fa-sync fa-spin' %>
      <%= tag.br %>
      <%= l :label_loading %>
    <% end %>
  <% end %>

  <%= content_for :render_async %>

  <%= javascript_tag do %>
      $(function() {
        $('#ajax-indicator').hide();
      })
  <% end %>  
<% else %>
  <%= render partial: 'dashboards/blocks/nodata', locals: { label: nil } %>
<% end %>

app/views/dashboards/blocks/_button.html.erb
<%
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
%>

<%= render partial: 'dashboards/blocks/button_block', locals: { block_id: block_id, settings: settings }%>

<% if @can_edit %>
  <%= tag.div id: "#{block_id}-settings", style: "display: none;" do %>
    <%= form_tag(update_layout_setting_dashboard_path(@dashboard), remote: true) do %>
      <%= render partial: 'dashboards/blocks/button_settings', locals: { block_id: block_id, settings: settings }%>
      <%= tag.p do %>
        <%= submit_tag l(:button_save) %>
        <%= link_to_function l(:button_cancel), "$('##{block_id}-settings').toggle();" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<%= tag.style do %>
 #<%= "block-#{block_id}" %> .button {
    background-color: <%= settings.fetch(:color, '#a8a7a7') %>;
  }
<% end %>

<%= javascript_tag do %>
  adjustCurserAtCenteredBlockItems('<%= "#block-#{block_id}" %>');
<% end %>

app/views/dashboards/blocks/_chart.html.erb
<%
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
%>

<% project = Project.find_by(id: settings[:project_id] ) %>
<%=tag.h3 "#{project&.name} #{RedmineDashboards::SEPARATOR} #{with_default(settings[:title], l(:label_report))}" %>
<% ordinate = settings.fetch(:filter, 'rows') %>
<% chart = DashboardBlockData.new(block_id, project, 'tracker_id', ordinate) %>

<% if chart.dataset.any? { |set| set[:data].any?(&:positive?) } %>
  <%= tag.div class: 'issue-report-graph' do %>
    <%= tag.canvas id: "#{block_id}_issues_by_#{chart.detail}" %>
  <% end %>

  <%= javascript_tag do %>
    function render<%= block_id.camelize %>(canvas_id, title, chartData){
    /* https://github.com/nagix/chartjs-plugin-colorschemes/blob/master/src/colorschemes/colorschemes.tableau.js » tableau.ClassicCyclic13 */
    let backgroundColors = ['#1f83b4', '#12a2a8', '#2ca030', '#78a641', '#bcbd22', '#ffbf50', '#ffaa0e', '#ff7f0e', '#d63a3a', '#c7519c', '#ba43b4', '#8a60b0', '#6f63bb'];
      var borderColors = [];
      for (var i = 0; i < chartData.datasets.length; i++) {
        chartData.datasets[i].backgroundColor = backgroundColors[i % backgroundColors.length];
        chartData.datasets[i].borderColor = borderColors[i % borderColors.length];
        chartData.datasets[i].borderWidth = 1;
      }
      new Chart($(canvas_id), {
        type: '<%= 'bar' %>',
        data: chartData,
        options: {
          indexAxis: '<%= (settings.fetch(:chart_type, 'bar') == 'horizontalBar') ? 'y' : 'x' %>',
          elements: {
            bar: { borderWidth: 2 }
          },
          responsive: true,
          scales: {
            x: { stacked: true, ticks: { precision: 0 } },
            y: { stacked: true, ticks: { precision: 0 } }
          },
          plugins: {
            legend: { 
              position: 'bottom',
              display: <%= RedmineDashboards.true? settings.fetch(:legend, true) %> },
            title: {
              display: true,
              text: title }
          }
        }
      });
    }
    $(document).ready(function(){
      var <%= block_id.camelize %> = {
        labels: <%= raw chart.labels.to_json %>,
        datasets: <%= raw chart.dataset.to_json %>
      };
      render<%= block_id.camelize %>("#<%= block_id %>_issues_by_<%= chart.detail %>", "<%= l(:label_issues_by, chart.report_title) %>", <%= block_id.camelize %>);
    });
  <% end %>
  <% content_for :header_tags do %>
      <style type="text/css">
      .issue-report-graph {
        width: auto;
        margin: 0 auto;
      }
      table.list td.name{
        word-wrap: break-word;
      }
    </style>
  <% end %>
<% else settings.present? %>
  <%= render partial: 'dashboards/blocks/nodata', locals: { label: nil } %>
<% end %>

<% if @can_edit %>
  <%= tag.div id: "#{block_id}-settings", style: 'display: none;' do %>
    <%= form_tag(update_layout_setting_dashboard_path(@dashboard), remote: true) do %>
      <%= render partial: 'dashboards/blocks/chart_settings', locals: { block_id: block_id, settings: settings }%>
      <%= tag.p do %>
        <%= submit_tag l(:button_save) %>
        <%= link_to_function l(:button_cancel), "$('##{block_id}-settings').toggle();" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/dashboards/blocks/_documents.html.erb
<%
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2016 - 2021 Alexander Meindl <https://github.com/alexandermeindl>, alphanodes.
# See <https://github.com/AlphaNodes/additionals>.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
%>

<%= tag.h3 l(:label_document_plural), class: 'icon icon-document' %>

<% if @can_edit %>
  <%= tag.div id: "#{block_id}-settings", style: 'display: none;' do %>
    <%= form_tag(update_layout_setting_dashboard_path(@dashboard), remote: true) do %>
      <%= tag.div class: 'box tabular settings' do %>
        <%= tag.p do %>
          <%= dashboards_settings_numberfield :max_entries,
                                              value: max_entries,
                                              tag_name: "settings[#{block_id}][max_entries]",
                                              min: 1, max: 100, required: true %>
        <% end %>
        <%= tag.p do %>
          <%= submit_tag l(:button_save) %>
          <%= link_to_function l(:button_cancel), "$('##{block_id}-settings').toggle();" %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<% if documents.any? %>
  <%= render partial: 'documents/document', collection: documents %>
  <%= tag.p do %>
    <% if @project %>
      <%= link_to l(:label_document_view_all), project_documents_path(@project) %>
    <% end %>
  <% end %>
<% else %>
  <%= render partial: 'dashboards/blocks/nodata', locals: { label: nil } %>
<% end %>

app/views/dashboards/blocks/_my_spent_time.html.erb
<%
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2016 - 2021 Alexander Meindl <https://github.com/alexandermeindl>, alphanodes.
# See <https://github.com/AlphaNodes/additionals>.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
%>

<%= tag.h3 block_object[:label] %>

<% if @can_edit %>
  <%= tag.div id: "#{block_id}-settings", style: 'display: none;' do %>
    <%= form_tag(update_layout_setting_dashboard_path(@dashboard), remote: true) do %>
      <%= render partial: 'dashboards/blocks/my_spent_time_settings', locals: { block_id: block_id, settings: settings }%>
      <%= tag.p do %>
        <%= submit_tag l(:button_save) %>
        <%= link_to_function l(:button_cancel), "$('##{block_id}-settings').toggle();" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<%= tag.div class: 'my-spent-time-block' do %>
  <% if settings[:table].to_i.positive? %>
    <%= render partial: 'my/blocks/timelog', locals: block_object.prepare_custom_locals(settings, @dashboard) %>
  <% else %>
    <%= tag.ul class: 'reporting-list' do %>
      <%= tag.li class: 'today' do %>
        <%= l(:label_today) %>: <%= l_hours_short entries_today.sum(&:hours) %>
      <% end %>
      <%= tag.li class: 'days' do %>
        <%=  l(:label_last_n_days, count: settings.fetch(:days, '7')) %>: <%= l_hours_short entries_days.sum(&:hours) %>
      <% end %>
    <% end %>

    <%= link_to l(:label_spent_time), _time_entries_path(@project, nil, user_id: 'me') %>
    <%= link_to l(:button_log_time),
                _new_time_entry_path(@project, nil),
                class: 'icon-only icon-add',
                title: l(:button_log_time) %>
  <% end %>
<% end %>