config/routes.rb
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

Rails.application.routes.draw do
  resource :dashboard_async_blocks, only: %i[show create]

  resources :dashboards do
    member do
      post :update_layout_setting
      post :add_block
      post :remove_block
      post :order_blocks
    end
  end
end

app/views/welcome/_sidebar.html.erb
<%
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2016 - 2021 Alexander Meindl <https://github.com/alexandermeindl>, alphanodes.
# See <https://github.com/AlphaNodes/additionals>.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
%>

<%= show(@dashboard).render_sidebar_dashboards  %>

app/views/welcome/index.html.erb
<%
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2016 - 2021 Alexander Meindl <https://github.com/alexandermeindl>, alphanodes.
# See <https://github.com/AlphaNodes/additionals>.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
%>

<%
# Some plugins use @news (e.g. redmine_wysiwyg_editor), to detect news
%> 
<% @news = nil %> 

<%=tag.div class: 'contextual' do %>
  <% if @dashboard&.editable? %>
    <%= link_to l(:button_dashboard_edit),
                edit_dashboard_path(@dashboard),
                class: 'icon icon-edit'%>
  <% end %>

  <%= call_hook :view_welcome_contextual_links %>

  <% if @dashboard&.editable? %>
    <%= form_tag(add_block_dashboard_path(@dashboard), remote: true, id: 'block-form', authenticity_token: true) do %>
      <%= show(@dashboard ).dashboard_block_select_tag %>
    <% end %>
  <% end %>

  <%= actions_dropdown do %>
    <% if User.current.allowed_to?(:manage_dashboards, nil, global: true) ||
          User.current.allowed_to?(:manage_own_dashboards, nil, global: true)  %>
      <%= link_to l(:label_new_dashboard),
                  new_dashboard_path,
                  class: 'icon icon-add new-additionals-dashboard' %>
    <% end %>
    <%= show(@dashboard).delete_dashboard_link dashboard_path(@dashboard) if @dashboard&.destroyable? %>
    <%= show(@dashboard).sidebar_action_toggle @dashboard_sidebar %>
    <%= show(@dashboard).render_dashboard_actionlist  unless @dashboard_sidebar %>

    <%= call_hook :view_welcome_show_actions_dropdown %>
  <% end if User.current.logged? %>
<% end %>

<%= tag.h2 show(@dashboard).headline %>

<%= call_hook :view_welcome_index_top %>

<%= render partial: 'common/dashboard', locals: { dashboard: @dashboard } %>

<%= call_hook :view_welcome_index_bottom %>

<% if @dashboard_sidebar %>
  <% content_for :sidebar do %>
    <%= render partial: 'sidebar' %>
    <%= call_hook :view_welcome_show_sidebar_bottom %>
  <% end %>
<% end %>

<% content_for :header_tags do %>
  <%= auto_discovery_link_tag :atom,
                            { controller: 'news',
                              action: 'index',
                              key: User.current.atom_key,
                              format: 'atom' },
                              title: "#{Setting.app_title}: #{l :label_news_latest}" %>
  <%= auto_discovery_link_tag :atom,
                            { controller: 'activities',
                              action: 'index',
                              key: User.current.atom_key,
                              format: 'atom' },
                              title: "#{Setting.app_title}: #{l :label_activity}" %>
<% end %>