config/routes.rb
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

Rails.application.routes.draw do
  resource :dashboard_async_blocks, only: %i[show create]

  resources :dashboards do
    member do
      post :update_layout_setting
      post :add_block
      post :remove_block
      post :order_blocks
    end
  end
end

app/views/common/_dashboard.html.erb
<%
# frozen_string_literal: true

# This file is part of the Plugin Redmine Dashboards.
#
# Copyright (C) 2016 - 2021 Alexander Meindl <https://github.com/alexandermeindl>, alphanodes.
# See <https://github.com/AlphaNodes/additionals>.
#
# Copyright (C) 2021-2023 Liane Hampe <liaham@xmera.de>, xmera Solutions GmbH.
#
# This plugin program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
%>


<%= call_hook :view_dashboard_top, dashboard: dashboard, project: @project %>
<%=tag.div id: 'my-page', class: "splitcontent #{show(dashboard).css_classes}" do %>
  <% dashboard.available_groups.each do |group| %>
    <% style = (dashboard.layout[group].present? && User.current.logged?) ?  'box' : 'disable'  %>
    <%= tag.div id: "list-#{group}", class: "block-receiver splitcontent#{group} #{style}" do %>
      <%= show(dashboard).render_dashboard_blocks dashboard.layout[group] %>
    <% end %>
  <% end %>
<% end %>

<%= call_hook :view_dashboard_bottom, dashboard: dashboard, project: @project %>

<%= context_menu %>

<%
# required for drap & drop work
# (this should always set, because to support new entries)
%>

<% include_calendar_headers_tags %>

<% if dashboard.content.with_chartjs? %>
  <% content_for :header_tags do %>
    <%= javascript_include_tag 'chart.min' %>
  <% end %>
<% end %>

<%= javascript_tag do %>
<%
  # Code for preventing vertical scroll jump is taken from 
  # https://stackoverflow.com/questions/1735372/jquery-sortable-list-scroll-bar-jumps-up-when-sorting#answer-32575012
%>
  $(function() {
    $('#block-select').val('');
    $('.block-receiver').mousedown(function() {
        // set fixed height to prevent scroll jump
        // when dragging from bottom
        $(this).height($(this).height());
    }).mouseup(function () {
        // set height back to auto 
        // when user just clicked on item
        $(this).height('auto');
    }).sortable({
      connectWith: '.block-receiver',
      tolerance: 'pointer',
      handle: '.sort-handle',
      start: function(event, ui){
        // dragging is happening
        // and scroll jump was prevented,
        // we can set it back to auto
        $(this).height('auto');
        $(this).parent().addClass('dragging');
      },
      stop: function(event, ui){$(this).parent().removeClass('dragging');},
      update: function(event, ui){
        // trigger the call on the list that receives the block only
        if ($(this).find(ui.item).length > 0) {
          $.ajax({
            url: "<%= escape_javascript order_blocks_dashboard_path(dashboard) %>",
            type: 'post',
            data: {
              'group': $(this).attr('id').replace(/^list-/, ''),
              'block_ids': $.map($(this).children(), function(el){return $(el).attr('id').replace(/^block-/, '');})
            }
          });
        }
      }
    });
  });
<% end %>